In [235]:
import numpy as np
import os, os.path
import matplotlib.image as matlib

In [236]:
plane = "axial"
mri_slice = "234"
mouse_x = 55
mouse_y = 99

In [237]:
npy_file = "../react-ui/src/assets/P57-16/mri/indices_" + plane + "_C_order/slice_" + str(mri_slice) + ".npy"

In [238]:
npy_slice_array = np.load(npy_file)

print(np.isfortran(npy_slice_array))
print(npy_slice_array.shape)
#print(npy_slice_array[45])

False
(224, 448)


In [239]:
# get the block number from the numpy array
block = npy_slice_array[mouse_x][mouse_y]
print(block)

24


In [240]:
# define a vector to be used later (to get the histology coords)
# an earlier version of this notebook did +1 to the mri_slice here, need to check if this is necessary.
# need to find out the correct order of params when creating the vector (depending on the current plane)
if block == 0:
    print("block number is 0, no further calculations are necessary as there is no associated histology")

if plane == "sagittal":
  mri_vector=np.array([float(mri_slice), float(mouse_y), float(mouse_x), 1.0])
elif plane == "coronal":
  mri_vector=np.array([float(mri_slice), float(mouse_y), float(mouse_x), 1.0])
elif plane == "axial":
  mri_vector=np.array([float(mouse_x), float(mouse_y), float(mri_slice), 1.0])

In [241]:
# open the matrix txt file
matrix_txt = open("../react-ui/src/assets/P57-16/mri/matrices/block_" + str(block) + ".txt")
read_matrix_txt = matrix_txt.read()

In [242]:
# parse the text file and convert it to an array
matrix = read_matrix_txt.replace('\n', ' ')
matrix = matrix.split(" ")
matrix = matrix[:-1] # pops the last element in the array

In [243]:
# convert the array of strings to an array of floats
matrix_as_floats = []
for item in matrix:
    matrix_as_floats.append(float(item))

In [244]:
# divide matrix array into chuncks to form a multidimensional array
def divide_chunks(l, n):
    for i in range(0, len(l), n): 
        yield l[i:i + n]

# how many elements should have
n = 4
  
chunked_array = list(divide_chunks(matrix_as_floats, n))
print(chunked_array)

[[-1.125857611340117, 1.686454240867989, 3.4696816516182043, -287.01308726922], [3.850630863147196, 0.6743281705488938, 0.8487940354417981, -319.6798952728896], [-0.03634574078131531, 0.5848713016547116, -0.28018555453244887, 19.08382028482923], [0.0, 0.0, 0.0, 1.0]]


In [245]:
transform = np.array(chunked_array)
print(transform)

[[-1.12585761e+00  1.68645424e+00  3.46968165e+00 -2.87013087e+02]
 [ 3.85063086e+00  6.74328171e-01  8.48794035e-01 -3.19679895e+02]
 [-3.63457408e-02  5.84871302e-01 -2.80185555e-01  1.90838203e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [246]:
blockvector = transform.dot(mri_vector)

In [247]:
print(blockvector)

[629.92922043 157.48109538   9.42364365   1.        ]


In [ ]:
# test_transform = np.array([[0.31385434307807203, -3.664457652247729, 1.6199030926177134, 666.0080271821023],
# [-0.7744411837137424, 1.4870493065731998, 3.6535143658756977, -139.31333561581766],
# [-1.2110952755381341, -0.18593341100766062, -0.1914204859080043, 118.27995513465419],
# [0.0, 0.0, 0.0, 1.0]])

In [11]:
histology = "../react-ui/src/assets/P57-16/histology"


In [12]:
folder = os.path.join(histology,"25")
slice_folder = os.path.join(folder,"slices_HE")
if os.path.exists(slice_folder):
    print(slice_folder)
else:
    print("the folder does not exist")
images = [name for name in os.listdir(slice_folder) if os.path.isfile(os.path.join(slice_folder, name))]
print(len(images))
image = None
if len(images) > 0:
    image = images[0]

../react-ui/src/assets/P57-16/histology/25/slices_HE
38


In [13]:
if not image == None:
    fullPath = os.path.join(slice_folder, image)
    readImage = matlib.imread(fullPath)
    print(readImage.shape)

(805, 552, 3)
