In [122]:
import numpy as np
import os, os.path
import matplotlib.image as matlib

In [123]:
plane = "axial"
mri_slice = "145"
mouse_x = 222
mouse_y = 90

In [124]:
npy_file = "../react-ui/src/assets/P57-16/mri/indices_" + plane + "/slice_" + str(mri_slice) + ".npy"

In [125]:
npy_slice_array = np.load(npy_file)

print(np.isfortran(npy_slice_array))
print(npy_slice_array.shape)

True
(224, 448)


In [126]:
# get the block number from the numpy array
block = npy_slice_array[mouse_x][mouse_y]
print(block)

0


In [131]:
# define a vector to be used later (to get the histology coords)
# an earlier version of this notebook did +1 to the mri_slice here, need to check if this is necessary.
# need to find out the correct order of params when creating the vector (depending on the current plane)
if block == 0:
    print("block number is 0, no further calculations are necessary as there is no associated histology")

if plane == "sagittal":
  mri_vector=np.array([float(mri_slice), float(mouse_y), float(mouse_x), 1.0])
elif plane == "coronal":
  mri_vector=np.array([float(mri_slice), float(mouse_y), float(mouse_x), 1.0])
elif plane == "axial":
  mri_vector=np.array([float(mouse_x), float(mouse_y), float(mri_slice), 1.0])

block number is 0, no further calculations are necessary as there is no associated histology


In [128]:
# open the matrix txt file
matrix_txt = open("../react-ui/src/assets/P57-16/mri/matrices/block_" + str(block) + ".txt")
read_matrix_txt = matrix_txt.read()

FileNotFoundError: [Errno 2] No such file or directory: '../react-ui/src/assets/P57-16/mri/matrices/block_0.txt'

In [129]:
# parse the text file and convert it to an array
matrix = read_matrix_txt.replace('\n', ' ')
matrix = matrix.split(" ")
matrix = matrix[:-1] # pops the last element in the array

In [112]:
# convert the array of strings to an array of floats
matrix_as_floats = []
for item in matrix:
    matrix_as_floats.append(float(item))

In [113]:
# divide matrix array into chuncks to form a multidimensional array
def divide_chunks(l, n):
    for i in range(0, len(l), n): 
        yield l[i:i + n]

# how many elements should have
n = 4
  
chunked_array = list(divide_chunks(matrix_as_floats, n))
print(chunked_array)

[[3.9918815921927324, 0.14203936785714244, 0.2353534993986506, -95.3126553016657], [0.16442745659295432, -1.3162776492428165, -3.803865995716457, 969.8247167526811], [-0.0112355845778312, 0.55207262125821, -0.23935829358640404, -4.480988935563403], [0.0, 0.0, 0.0, 1.0]]


In [114]:
transform = np.array(chunked_array)
print(transform)

[[ 3.99188159e+00  1.42039368e-01  2.35353499e-01 -9.53126553e+01]
 [ 1.64427457e-01 -1.31627765e+00 -3.80386600e+00  9.69824717e+02]
 [-1.12355846e-02  5.52072621e-01 -2.39358294e-01 -4.48098894e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [115]:
blockvector = transform.dot(mri_vector)

In [116]:
print(blockvector)

[273.66119988 324.96428177   4.61985847   1.        ]


In [ ]:
# test_transform = np.array([[0.31385434307807203, -3.664457652247729, 1.6199030926177134, 666.0080271821023],
# [-0.7744411837137424, 1.4870493065731998, 3.6535143658756977, -139.31333561581766],
# [-1.2110952755381341, -0.18593341100766062, -0.1914204859080043, 118.27995513465419],
# [0.0, 0.0, 0.0, 1.0]])

In [11]:
histology = "../react-ui/src/assets/P57-16/histology"


In [12]:
folder = os.path.join(histology,"25")
slice_folder = os.path.join(folder,"slices_HE")
if os.path.exists(slice_folder):
    print(slice_folder)
else:
    print("the folder does not exist")
images = [name for name in os.listdir(slice_folder) if os.path.isfile(os.path.join(slice_folder, name))]
print(len(images))
image = None
if len(images) > 0:
    image = images[0]

../react-ui/src/assets/P57-16/histology/25/slices_HE
38


In [13]:
if not image == None:
    fullPath = os.path.join(slice_folder, image)
    readImage = matlib.imread(fullPath)
    print(readImage.shape)

(805, 552, 3)
